FROM node:16-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

ENV REACT_APP_BACKEND_URL http://localhost:8000

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html