FROM node:16-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL http://localhost:8000

RUN npm run build \

    npm install -g serve \

    adduser -S appuser

USER appuser

ENTRYPOINT ["serve", "-s", "-l", "5000", "build"]